logging:
  level:
    com.kajan: DEBUG
#    org.springframework.security: DEBUG
#    com.github.sardine: DEBUG
#    org.springframework.ldap: DEBUG
#    org.camunda.bpm.springboot: DEBUG

testing: false

camunda.bpm:
  admin-user:
    id: kajan
    password: kajan
    firstName: Kajan
  filter:
    create: All tasks

spring:
  profiles:
    active: h2, nginx-local-s, testing

  security:
    oauth2:
      client:
        registration:
          nextcloud:
            client-id: 54YBNb0fv566OfExSlxHjCPVKR73ljKhnOmP9rjVNQLTByMDBfwAE0TQGHYxuzzc
            client-secret: jcNkqCokM5Z4QvHKeoo4UaqLWetoXUAwtiuAhxbqsqFJf7bGDJs06EgLKRhsQcQb
            redirect-uri-template: http://iworkflows.projects.mrt.ac.lk:4200/connect/nextcloud
            authorization-grant-type: authorization_code
            client-name: NextCloud
            scope: read, write
          google:
            client-id: 1006906289665-gnqn7aq78n707c2glp580jf5lk26lbs1.apps.googleusercontent.com
            client-secret: FDfO-FBzTlFUT3k7r7WYubYk
            redirect-uri-template: http://iworkflows.projects.mrt.ac.lk:4200/token/code/google
          learnorg:
            client-id: iworkflows_server_test
            client-secret: 688b10e0d1033410e214ebe6c27f0449609819e6b6593809
            redirect-uri-template: http://iworkflows.projects.mrt.ac.lk:4200/connect/learnorg
            authorization-grant-type: authorization_code
            client-name: LearnOrg
            scope: profile
        provider:
          nextcloud:
            authorization-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/authorize
            token-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/api/v1/token
          learnorg:
            authorization-uri: http://10.8.90.4/oauth/login.php
            token-uri: http://10.8.90.4/oauth/token.php

moodle:
  name: Moodle
  redirect-uri: /moodle/token
  uri:
    root: http://iworkflows.projects.mrt.ac.lk/moodle
    webservice: http://iworkflows.projects.mrt.ac.lk/moodle/webservice/rest/server.php?wstoken={wstoken}&wsfunction={wsfunction}&moodlewsrestformat=json
    token: http://iworkflows.projects.mrt.ac.lk/moodle/login/token.php?username={username}&password={password}&service={ws-short-name}
  wsshortname: moodle_mobile_app
  wsfunction:
    get-courses-by-field: core_course_get_courses_by_field
    get-assignments: mod_assign_get_assignments

nextcloud:
  uri:
    root: http://iworkflows.projects.mrt.ac.lk/nextcloud/ocs/v1.php/cloud/users/{userid}
    userinfo: http://iworkflows.projects.mrt.ac.lk/nextcloud/ocs/v1.php/cloud/users/{userid}
    ocs-share-api: http://iworkflows.projects.mrt.ac.lk/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares
    file: http://iworkflows.projects.mrt.ac.lk/nextcloud/remote.php/dav/files

iworkflows:
  credentials:
    nextcloud:
      username: iworkflows
      password: iworkflows
    learnorg:
      username: iworkflows
      password: iworkflows

learnorg:
  uri:
    system: https://10.8.90.4/oauth/iworkflows.php?wsfunction={wsfunction}
    userinfo: http://10.8.90.4/oauth/user_info.php
  wsfunction:
    get-department-head: get_head_by_department
    set-approved-leave: set_leave_taken
#server:
#  ssl:
#    key-store-type: PKCS12
#    ssl.key-store: file:baeldung.p12
#    key-password: baeldung
#    key-alias: baeldung
#    enabled: false
#security:
#  require-ssl: true
---
spring:
  profiles: h2

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #       url: jdbc:h2:mem:iworkflows
    url: jdbc:h2:file:~/db/iworkflows
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: angular-local

  security:
    oauth2:
      client:
        registration:
          nextcloud:
            client-id: 7OiShZdlpyzvZYgUZ3gPt8aveCyWGh46715CBqeqfGmlAHGf4skyglgZ9zx6TF3p
            client-secret: 07SxAA19BWzRBr65GGjsqcsXrzBeAA9n7ArfwkLAkddKaZCxhrAK9ERmdn93Uyil
            redirect-uri-template: http://localhost:4200/connect/nextcloud
            authorization-grant-type: authorization_code

            client-name: NextCloud
            scope: read, write
          learnorg:
            client-id: iworkflows
            client-secret: 12ba3150f57cafbc63943bed9605b9395d158b47038b1931
            redirect-uri-template: http://localhost:4200/connect/learnorg
            authorization-grant-type: authorization_code
            client-name: LearnOrg
            scope: profile

        provider:
          nextcloud:
            authorization-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/authorize
            token-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/api/v1/token
          learnorg:
            authorization-uri: https://10.8.90.4/oauth/login.php
            token-uri: https://10.8.90.4/oauth/token.php

---
spring:
  profiles: nginx-local

  security:
    oauth2:
      client:
        registration:
          nextcloud:
            client-id: QArWjXEMv9cwWBPmMsSLH6H1lvliOWoz4ZUmNJdmqeG0RJEzD8SbduFYg3lysALF
            client-secret: 0EglGAu6nS7j2irThKYQD5bJZlGZbHHWEBlK5ydi85163QeGS7IMLLgAF7wmWAaK
            redirect-uri-template: http://localhost:80/connect/nextcloud
            authorization-grant-type: authorization_code
            client-name: NextCloud
            scope: read, write
          learnorg:
            client-id: iworkflows
            client-secret: 12ba3150f57cafbc63943bed9605b9395d158b47038b1931
            redirect-uri-template: http://localhost:4200/connect/learnorg
            authorization-grant-type: authorization_code
            client-name: LearnOrg
            scope: profile

        provider:
          nextcloud:
            authorization-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/authorize
            token-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/api/v1/token
          learnorg:
            authorization-uri: https://10.8.90.4/oauth/login.php
            token-uri: https://10.8.90.4/oauth/token.php


---
spring:
  profiles: nginx-local-s

  security:
    oauth2:
      client:
        registration:
          asana:
            client-id: 923555116588679
            client-secret: 0ddf1489941f8b88125d607b79fef6fb
            redirect-uri-template: https://localhost/connect/asana
            authorization-grant-type: authorization_code
            client-name: Asana
            scope: default
          github:
            client-id: dad2aeed19ee40c70c92
            client-secret: 29e9d576e72f7b86b8fe34e0e44160b1ddd27678
            redirect-uri-template: https://localhost/connect/github
#            authorization-grant-type: authorization_code
            client-name: GitHub
          nextcloud:
            client-id: 28ZLbXzqcdRwLAdWc0hW7QT6ZHT54kWtrHq7KViOi7wT9k6DggiwWp2CGumZHlkJ
            client-secret: 4jCVVlYQT7bdsk150byltrABPFxOz4QGx86eveC4LNaVZFKkrevAx8W6xqecjfYK
            redirect-uri-template: https://localhost/connect/nextcloud
            authorization-grant-type: authorization_code
            client-name: NextCloud
            scope: read, write
          learnorg:
            client-id: iworkflows
            client-secret: 12ba3150f57cafbc63943bed9605b9395d158b47038b1931
            redirect-uri-template: http://localhost:4200/connect/learnorg
            authorization-grant-type: authorization_code
            client-name: LearnOrg
            scope: profile

        provider:
          asana:
            authorization-uri: https://app.asana.com/-/oauth_authorize
            token-uri: https://app.asana.com/-/oauth_token
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
          nextcloud:
            authorization-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/authorize
            token-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/api/v1/token
          learnorg:
            authorization-uri: https://10.8.90.4/oauth/login.php
            token-uri: https://10.8.90.4/oauth/token.php

---
spring:
  profiles: testing

testing: true