logging:
  level:
    com.kajan: DEBUG
    org.springframework.security: DEBUG

spring:
  profiles:
    active: h2

  security:
    oauth2:
      client:
        registration:
          nextcloud:
            client-id: 7OiShZdlpyzvZYgUZ3gPt8aveCyWGh46715CBqeqfGmlAHGf4skyglgZ9zx6TF3p
            client-secret: 07SxAA19BWzRBr65GGjsqcsXrzBeAA9n7ArfwkLAkddKaZCxhrAK9ERmdn93Uyil
            redirect-uri-template: http://localhost:4200/connect/nextcloud
            authorization-grant-type: authorization_code
            client-name: NextCloud
            scope: read, write
          google:
            client-id: 1006906289665-gnqn7aq78n707c2glp580jf5lk26lbs1.apps.googleusercontent.com
            client-secret: FDfO-FBzTlFUT3k7r7WYubYk
            redirect-uri-template: http://localhost:8080/token/code/google
        provider:
          nextcloud:
            authorization-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/authorize
            token-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/api/v1/token

moodle:
  name: Moodle
  redirect-uri: /moodle/token
  uri:
    root: http://iworkflows.projects.mrt.ac.lk/moodle
    webservice: http://iworkflows.projects.mrt.ac.lk/moodle/webservice/rest/server.php?wstoken={wstoken}&wsfunction={wsfunction}&moodlewsrestformat=json
    token: http://iworkflows.projects.mrt.ac.lk/moodle/login/token.php?username={username}&password={password}&service={ws-short-name}
  wsshortname: moodle_mobile_app
  wsfunction:
    get-courses-by-field: core_course_get_courses_by_field
    get-assignments: mod_assign_get_assignments

nextcloud:
  uri:
    root: http://localhost:8090/nextcloud/ocs/v1.php/cloud/users/{userid}
    userinfo: http://localhost:8090/nextcloud/ocs/v1.php/cloud/users/{userid}
    file: http://localhost:8090/nextcloud/remote.php/dav/files/{userid}/{path-to-file}

msg:
  connect:
    success: Successfully connected with {provider}
    fail: Unable to connect to {provider}, please try again
  disconnect:
    success: Successfully disconnected from {provider}
    fail: Unable to disconnect from {provider}, please try again
---
spring:
  profiles: h2

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #       url: jdbc:h2:mem:iworkflows
    url: jdbc:h2:file:~/db/iworkflows
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update

---
spring:
  profiles: ldap

  ldap:
    embedded:
      base-dn: dc=springframework,dc=org
      ldif: classpath:test-server.ldif
      port: 8389
      url: ldap://localhost:8389/

---
spring:
  profiles: server

  security:
    oauth2:
      client:
        registration:
          nextcloud:
            client-id: Bcwh8FjxJdrPfMH92VWDDOP74RaZjCCjqy32nhI5HG7pJC1UByL7l0ZL0eAFRDfr
            client-secret: bt5b7s5J9HiKJne7hBKhhZvjnyXp3iWpJj1kkPuBje4S9ydtlle7g2ZI8bruu1Dg
            redirect-uri-template: http://iworkflows.projects.mrt.ac.lk:8080/token/code/nextcloud
            authorization-grant-type: authorization_code
            client-name: NextCloud
            scope: read, write

        provider:
          nextcloud:
            authorization-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/authorize
            token-uri: http://iworkflows.projects.mrt.ac.lk/nextcloud/index.php/apps/oauth2/api/v1/token

nextcloud:
  uri:
    root: http://iworkflows.projects.mrt.ac.lk/nextcloud/ocs/v1.php/cloud/users/{userid}
    userinfo: http://iworkflows.projects.mrt.ac.lk/nextcloud/ocs/v1.php/cloud/users/{userid}
    file: http://iworkflows.projects.mrt.ac.lk/nextcloud/remote.php/dav/files/{userid}/{path-to-file}


---
spring:
  profiles: angular

  security:
    oauth2:
      client:
        registration:
          nextcloud:
            client-id: ifYTmneaFMWjjU0abuWnpEviuYEZQe7lmSxWktJGInmBWCYbtMyLiaqAB3f7aR7q
            client-secret: OljKGNJ5LgsorA3WqngJLOiRfn8vgTUdGXA1am3ePOcJQwD54H0L69se0mL69J21
            redirect-uri-template: http://localhost:4200/connect/nextcloud
            authorization-grant-type: authorization_code
            client-name: NextCloud
            scope: read, write

        provider:
          nextcloud:
            nextcloud:
              authorization-uri: http://localhost:8090/nextcloud/index.php/apps/oauth2/authorize
              token-uri: http://localhost:8090/nextcloud/index.php/apps/oauth2/api/v1/token

